apiVersion: batch/v1
kind: Job
metadata:
  name: vitamin-p-inference-mif-2014-0938-set8
  namespace: yn-gpu-workload
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
        nvidia.com/gpu.product: "NVIDIA-H100-80GB-HBM3"
      securityContext:
        runAsUser: 297724
        runAsGroup: 1944303352
        fsGroup: 1944303352
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '1000Gi'
        - name: program
          persistentVolumeClaim:
            claimName: yshokrollahi-gpu-rsrch9-home-plm
      containers:
        - name: inference-container
          image: hpcharbor.mdanderson.edu/yshokrollahi/vitamin-p:latest
          command:
            - /bin/bash
            - -c
            - |
              # Remove macOS hidden files
              find "/rsrch9/home/plm/idso_fa1_pathology/TIER1/patient-mosaic/2014-0938/MOSAIC/DSP/MOSAIC DSP Set 8/Images/DSP Scans" -name "._*" -type f -delete
              
              # Run inference
              python scripts/run_wsi_inference.py \
                --model_type flex \
                --model_size large \
                --checkpoint checkpoints/vitamin_p_flex_large_fold21_best.pth \
                --wsi_folder "/rsrch9/home/plm/idso_fa1_pathology/TIER1/patient-mosaic/2014-0938/MOSAIC/DSP/MOSAIC DSP Set 8/Images/DSP Scans" \
                --wsi_extension ome.tiff \
                --output_dir inference_dsp/2014-0938-mif-slides \
                --branch mif_nuclei \
                --device cuda \
                --patch_size 512 \
                --overlap 64 \
                --target_mpp 0.4004 \
                --magnification 20 \
                --clean_overlaps \
                --save_geojson \
                --detection_threshold 0.5 \
                --min_area_um 5.0 \
                --mif_nuclear_channel 0 \
                --mif_membrane_channels 1,2 \
                --mif_membrane_combination max \
                --filter_tissue \
                --tissue_threshold 0.01
          workingDir: /rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p-latest
          env:
            - name: HOME
              value: /tmp
            - name: PYTHONPATH
              value: /rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p-latest
          volumeMounts:
            - name: shm
              mountPath: "/dev/shm"
            - name: program
              mountPath: "/rsrch9/home/plm/idso_fa1_pathology"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "30"
              memory: "350Gi"
      restartPolicy: Never