---
apiVersion: batch/v1
kind: Job
metadata:
  name: yshokrollahi-vitamin-p
  namespace: yn-gpu-workload
  labels:
    k8s-user: yshokrollahi
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      securityContext:
        runAsUser: 297724
        runAsGroup: 1944303352
        fsGroup: 1944303352
        supplementalGroups:
          - 1944271327
          - 900027
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '21Gi'
        - name: program
          persistentVolumeClaim:
            claimName: yshokrollahi-gpu-rsrch9-home-plm
      containers:
        - name: main
          image: hpcharbor.mdanderson.edu/yshokrollahi/vitamin-p:latest
          command: ["python", "/rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p/main.py"]
          workingDir: /rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p
          env:
            - name: HOME
              value: /tmp
            - name: PYTHONPATH
              value: /rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
          volumeMounts:
            - name: shm
              mountPath: "/dev/shm"
            - name: program
              mountPath: "/rsrch9/home/plm/idso_fa1_pathology"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "32Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "16"
              memory: "32Gi"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never