apiVersion: batch/v1
kind: Job
metadata:
  name: yshokrollahi-vitamin-p-mif
  namespace: yn-gpu-workload
  labels:
    k8s-user: yshokrollahi
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        "nvidia.com/gpu.present": "true"
      securityContext:
        runAsUser: 297724
        runAsGroup: 900027
        fsGroup: 900027
      containers:
        - name: main
          image: hpcharbor.mdanderson.edu/yshokrollahi/cellvit@sha256:0b9813cd0c39eb4f8e2f5293a29f47379eb9c0f850540c39ed8f7cdd0129dcaf
          command: ["/usr/bin/python3", "/rsrch5/home/plm/yshokrollahi/vitamin-p-mIF/main.py"]
          workingDir: "/rsrch5/home/plm/yshokrollahi/vitamin-p-mIF"
          env:
            - name: HOME
              value: "/rsrch5/home/plm/yshokrollahi/"
            - name: CODE_DIR
              value: "/rsrch5/home/plm/yshokrollahi/vitamin-p-mIF"
            - name: DATA_DIR
              value: "/rsrch5/home/plm/yshokrollahi/data/tissuenet_v1.1"
            - name: PYTHONPATH
              value: "/rsrch5/home/plm/yshokrollahi/vitamin-p-mIF"
          volumeMounts:
            - name: shm
              mountPath: "/dev/shm"
            - name: home
              mountPath: "/rsrch5/home/plm/yshokrollahi/"
          resources:
            limits:
              nvidia.com/gpu: "1"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '21474836480'
        - name: home
          persistentVolumeClaim:
            claimName: yshokrollahi-gpu-home