apiVersion: batch/v1
kind: Job
metadata:
  name: vitamin-p-gan-pix2pix-fold6-improved
  namespace: yn-gpu-workload
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
        nvidia.com/gpu.product: "NVIDIA-H100-80GB-HBM3"
      securityContext:
        runAsUser: 297724
        runAsGroup: 1944303352
        fsGroup: 1944303352
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '1000Gi'
        - name: program
          persistentVolumeClaim:
            claimName: yshokrollahi-gpu-rsrch9-home-plm
      containers:
        - name: training-container
          image: hpcharbor.mdanderson.edu/yshokrollahi/vitamin-p:latest
          command: 
            - "python"
            - "scripts/train_gan.py"
            - "--fold"
            - "6"
            - "--epochs"
            - "250"
            # Loss weights
            - "--lambda_l1"
            - "100"
            - "--lambda_perceptual"
            - "10"
            - "--lambda_ssim"
            - "5"
            - "--lambda_gradient"
            - "5"
            # Architecture (all enabled by default, use --no-* to disable)
            # - "--no-perceptual"      # Uncomment to disable perceptual loss
            # - "--no-ssim"            # Uncomment to disable SSIM loss
            # - "--no-gradient"        # Uncomment to disable gradient loss
            # - "--no-attention"       # Uncomment to disable attention gates
            # - "--no-spectral-norm"   # Uncomment to disable spectral norm
            - "--n_residual_blocks"
            - "4"
            # - "--no-mixed-precision" # Uncomment to disable mixed precision
            - "--gradient_clip"
            - "5.0"
            # W&B
            - "--wandb-project"
            - "vitamin-p-gan"
          workingDir: /rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p-latest
          env:
            - name: WANDB_API_KEY
              value: "979fc21fe6b28c4e4a4503f7e421bfc270a4300c"
            - name: WANDB_PROJECT
              value: "vitamin-p-gan"
            - name: WANDB_MODE
              value: "online"
            - name: HOME
              value: /tmp
            - name: PYTHONPATH
              value: /rsrch9/home/plm/idso_fa1_pathology/codes/yshokrollahi/vitamin-p-latest
          volumeMounts:
            - name: shm
              mountPath: "/dev/shm"
            - name: program
              mountPath: "/rsrch9/home/plm/idso_fa1_pathology"
          resources:
            limits:
              nvidia.com/gpu: "2"
              cpu: "60"
              memory: "700Gi"
      restartPolicy: Never