# configs/training_config.yaml
epochs: 100
early_stopping_patience: 20
model_checkpoint_path: 'models/checkpoints/model.h5'
final_model_path: 'models/saved_models/final_model.h5'
encoder_model_path: 'models/saved_models/encoder_model.h5'
warmup_epochs: 5  # Added warmup epochs